### ISSUE TITLE
Multiline shortcodes

### ISSUE THREAD

**Issue by nsrosenqvist** [maiorano84/shortcodes#10]
I don't seem to be able to get the regex from parseShortcode to match multiline shortcodes. Is it supposed to be able to?

**Comment by maiorano84** [comment]
Not sure I follow what you mean by "multiline shortcode". Can you give me an example of your code, and what exactly you're trying to parse?

**Comment by maiorano84** [comment]
Just for further clarification:

The [DefaultParser](https://github.com/maiorano84/shortcodes/blob/v1.2.2/src/Parsers/DefaultParser.php#L84) contains a link in its comments pointing you to the [source regex](https://core.trac.wordpress.org/browser/tags/4.2/src/wp-includes/shortcodes.php#L224) that Wordpress itself used in version 4.2 to read in shortcodes. [The Regex hasn't really changed since then](https://core.trac.wordpress.org/browser/tags/5.4.1/src/wp-includes/shortcodes.php#L249).

If Wordpress' regex doesn't handle your particular use-case, then unfortunately mine won't either.

If you need to extend or expand upon how Shortcodes are parsed beyond what Wordpress already does, then you're able to roll your own Parser. As long as your class implements the [ParserInterface](https://github.com/maiorano84/shortcodes/blob/v1.2.2/src/Parsers/ParserInterface.php), you should be good.

Note that [Version 2](https://github.com/maiorano84/shortcodes/releases) is in Beta release. For all intents and purposes, I'm pretty sure it's stable but I'll need to flesh out my integration tests more to know for sure.

If you intend on rolling your own Parser, I would build it using the Beta version to avoid any breaking changes after release. If you find anything my tests haven't covered for, I'm open to additional issues and PRs.

**Comment by nsrosenqvist** [comment]
I was writing an extensive example with a bunch of different test cases and what each yielded as result for me, but now when I'm trying it out today everything works just as it should. I guess I must have been doing something very wrong somewhere...

Thanks for being so quick to respond!

**Comment by maiorano84** [comment]
@nsrosenqvist No problem, man! Opening your issue caused me to start revising my tests and updating some items, so thank you for reaching out! It's encouraging to know that people are still using this.
