### ISSUE TITLE
Docs are invalid

### ISSUE THREAD

**Issue by JarJak** [maiorano84/shortcodes#3]
```
echo $manager->doShortcode('[foo][bar/][/foo]'); //Outputs: foobar
echo $manager->doShortcode('[foo][baz/][/foo]'); //Outputs: foo[baz/]
```

this part of readme probably does miss something

**Comment by maiorano84** [comment]
@JarJak I'm not quite following what this issue is attempting to highlight. Did you need further clarification on something? Can you add some details in regards to what you're having trouble with?

**Comment by JarJak** [comment]
This part of readme says that executing same method with similar parameter results in different result and there is nothing about context or additional parameters that could change it's behavior, so I am assuming one of these lines is wrong.

**Comment by maiorano84** [comment]
@JarJak They are not the same parameter.

Note that in the first example, the parameter string is `[foo][bar/][/foo]`. The nested shortcode in the middle of this string reads **bar**.

In the second example, the parameter string is `[foo][baz/][/foo]`. The nested shortcode in the middle of this string reads **baz**.

This is highlighting the **Selective** behavior of the library, which is the default behavior. Note the block of code in this setup above the portion in the docs you highlighted:

> ... To handle this, there are several avenues we can take. Let's set up a manager that uses three shortcodes:

```
$manager = new ShortcodeManager([
    'foo' => new Library\SimpleShortcode('foo', null, function ($content) {
        return 'foo' . $this->manager->doShortcode($content, 'bar');
    }),
    'bar' => new Library\SimpleShortcode('bar', null, function ($content) {
        return 'bar' . $content;
    }),
    'baz' => new Library\SimpleShortcode('baz', null, function () {
        return 'baz';
    })
]);
```

> [foo] - Render shortcode as text with content appended that permits [bar] to be processed
> [bar] - Render shortcode as text with content appended
> [baz] - Render shortcode as text

The callback defined in `foo` allows `bar` to be processed as a nested shortcode, but not `baz`.

That's why `echo $manager->doShortcode('[foo][bar/][/foo]');` will yield `foobar`, and `echo $manager->doShortcode('[foo][baz/][/foo]');` will yield `foo[baz/]`.

Hopefully this will clarify things for you.

**Comment by JarJak** [comment]
Now it is clear, thanks :)
